updates azure/travis

diff --git a/.azure-pipelines/test-template.yml b/.azure-pipelines/test-template.yml
--- a/.azure-pipelines/test-template.yml
+++ b/.azure-pipelines/test-template.yml
@@ -9,31 +9,26 @@ parameters:
 
 steps:
 - script: |
+    # getting updated environment (CUDA_HOME, PATH, ..)
+    if [ -f $HOME/.tmprc ]; then source $HOME/.tmprc; fi
     WORKDIR=`pwd`
     # test example
-    testdir=${{ parameters.workingDirectory }}
+    dir=${{ parameters.workingDirectory }}
     echo "work directory: $WORKDIR"
-    echo "test directory: $testdir"
+    echo "test directory: $dir"
     echo ""
     cd $dir
-    echo "current dir: `pwd`"
-    echo ""
-    ls -al
-    echo ""
-    # fails to run..
-    #./run_this_example.sh
-    ## checks script return code
-    #if [[ $? -ne 0 ]]; then
-    #  # cleanup
-    #  rm -rf OUTPUT_FILES* DATABASES_MPI*
-    #  exit 1
-    #fi
 
-- bash: . './run_this_example.sh'
-  displayName: 'run this example'
-  workingDirectory: ${{ parameters.workingDirectory }}
+    ./run_this_example.sh
 
-- script: |
+    # checks script return code
+    if [[ $? -ne 0 ]]; then
+      echo "run failed, exiting..."
+      # cleanup
+      rm -rf OUTPUT_FILES* DATABASES_MPI*
+      exit 1
+    fi
+
     # checks output
     echo "testing seismograms:"
     echo "workdir: $WORKDIR"
@@ -45,6 +40,7 @@ steps:
     ./compare_seismogram_correlations.py REF_SEIS/ OUTPUT_FILES/ | grep min/max | cut -d \| -f 3 | awk '{print "correlation:",$1; if ($1 < 0.999 ){print $1,"failed"; exit 1;}else{ print $1,"good"; exit 0;}}'
     if [[ $? -ne 0 ]]; then exit 1; fi
     rm -rf OUTPUT_FILES/
-  displayName: 'Run Test ${{ parameters.workingDirectory }}'
+
+  displayName: 'Run Test - ${{ parameters.workingDirectory }}'
 
 
